models:
  default:
    model: meta/llama3-8b-instruct
    base_url: https://integrate.api.nvidia.com/v1
    api_key: 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

guards:
  finance_related:
    check:
      - query_type: context
        include:
          - finance
          - stock
          - investment
          - trading
          - portfolio
        exclude:
          - coronavirus
          - covid-19
          - pandemic

responses:
  default:
    - I'm sorry, but I can only provide information related to finance and stocks.
  finance_related:
    - Proceed
